### ISSUE TITLE
Use media_sessions to prevent connection to dc every time in get_file

### ISSUE THREAD

**Issue by annihilatorrrr** [PyrogramMod/PyrogramMod#14]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

```
session = Session(
                self, dc_id,
                await Auth(self, dc_id, await self.storage.test_mode()).create()
                if dc_id != await self.storage.dc_id()
                else await self.storage.auth_key(),
                await self.storage.test_mode(),
                is_media=True
            )
```
When we are uploading a big file, we get auth floods, to prevent it we can use media_sessions to get session ig 😅

```
session = self.media_sessions.get(dc_id)
if not session:
      session = self.media_sessions[dc_id] = Session(....
                    )
      await session.start()
```

**Comment by null-nick** [comment]
f06d2a2a

**Comment by annihilatorrrr** [comment]
Thanks.

**Comment by annihilatorrrr** [comment]
> > [157e8d4](https://github.com/PyrogramMod/PyrogramMod/commit/157e8d460f96a2401b54a104910dc5163ff3a69c)
> 
> why reverted ?

https://github.com/PyrogramMod/PyrogramMod/commit/157e8d460f96a2401b54a104910dc5163ff3a69c#commitcomment-134728979
